#train_config.yaml
hyperparams:
  img_data_path: 'data/processed'
  csv_data_path: 'data/processed/data2.csv'
  img_rescale: 122
  batch_size: 32 #same as paper
  shuffle: True
  num_epoch: 2
  seed: 123
  lr: 0.0001 #same as paper
