#train_config.yaml
hyperparams:
  img_data_path: 'data/processed/imgs/'
  csv_data_path: 'data/processed/data.csv'
  img_rescale: 122
  crop_ratio: 0.45
  batch_size: 32 #same as paper
  shuffle: True
  num_epoch: 30
  seed: 294
  lr: 0.0005 #same as paper
