#train_config3.yaml
hyperparams:
  comment: "0405and1605and0106and1506 data First test of network3 with lowpass filtered data"
  exp_group: "Lowpass filter experiments"
  img_data_path: "/work3/s203129/lowpassfiltered/imgs/" #/work3/s203129/0405and1605new/imgs/ data/processed/imgs/
  csv_data_path: "/work3/s203129/lowpassfiltered/data.csv" #/work3/s203129/0405and1605new/data.csv data/processed/data.csv
  img_rescale: 122
  crop_ratio: 0.45
  batch_size: 32 #32 #same as paper
  shuffle: True
  num_epoch: 20
  seed: 199
  lr: 0.001 #0.0001 same as paper