#train_config.yaml
hyperparams:
  img_data_path: '/work3/s203129/0405and1605/imgs/' #data/processed/imgs/
  csv_data_path: '/work3/s203129/0405and1605/data.csv' #data/processed/data.csv
  img_rescale: 122
  crop_ratio: 0.45
  batch_size: 32 #32 #same as paper
  shuffle: True
  num_epoch: 20
  seed: 634
  lr: 0.0001 #0.0001 same as paper
