#train_config2.yaml
hyperparams:
  comment: "Baseline for new copy-network"
  exp_group: "Network with imu input"
  img_data_path: "/work3/s203129/0405and1605and1506new/imgs/" #/work3/s203129/0405and1605new/imgs/ data/processed/imgs/
  csv_data_path: "/work3/s203129/0405and1605and1506new/data.csv" #/work3/s203129/0405and1605new/data.csv data/processed/data.csv
  img_rescale: 122
  crop_ratio: 0.45
  batch_size: 32 #32 #same as paper
  shuffle: True
  num_epoch: 30
  seed: 305
  lr: 0.001 #0.0001 same as paper
