#train_config.yaml
hyperparams:
  comment: "0405and1605 data batchnorm on all conv and lin lr is 0.01"
  img_data_path: "/work3/s203129/0405and1605/imgs/" #data/processed/imgs/ #
  csv_data_path: "/work3/s203129/0405and1605/data.csv" #data/processed/data.csv
  img_rescale: 122
  crop_ratio: 0.45
  batch_size: 32 #32 #same as paper
  shuffle: True
  num_epoch: 30
  seed: 868
  lr: 0.0001 #0.0001 same as paper [0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005, 0.01]
