#train_config.yaml
hyperparams:
  img_data_path: data/processed/imgs/ #'/work3/s203129/0405and1605/imgs/'
  csv_data_path: data/processed/data.csv  #'/work3/s203129/0405and1605/data.csv'
  img_rescale: 122
  crop_ratio: 0.45
  batch_size: 32 #32 #same as paper
  shuffle: True
  num_epoch: 30
  seed: 868
  lr: 0.01 #0.0001 same as paper [0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005, 0.01]
